server:
  port: 8080
spring:
  main:
    allow-circular-references: true
  liquibase:
    enabled: true
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/rs24?currentSchema=rs24schem
    username: postgres
    password: postgres
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQL95Dialect
    hibernate:
      ddl-auto: none